object frmEqualizerDLG: TfrmEqualizerDLG
  Left = 452
  Top = 270
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'Equalizer'
  ClientHeight = 266
  ClientWidth = 340
  Color = 15790320
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object layoutEqualizer: TdxLayoutControl
    Left = 0
    Top = 18
    Width = 340
    Height = 248
    Align = alClient
    ParentBackground = True
    TabOrder = 0
    AutoContentSizes = [acsWidth, acsHeight]
    LookAndFeel = datMain.layoutLookFeelMain_Web
    object Panel37: TPanel
      Left = 4
      Top = 7
      Width = 150
      Height = 13
      BevelOuter = bvNone
      Color = 10526880
      TabOrder = 11
    end
    object Panel38: TPanel
      Left = 4
      Top = 228
      Width = 150
      Height = 13
      BevelOuter = bvNone
      Color = 10526880
      TabOrder = 12
    end
    object lblPreset: TcxLabel
      Left = 134
      Top = 205
      Width = 35
      Height = 17
      Cursor = crHandPoint
      Caption = 'Preset'
      ParentColor = False
      ParentFont = False
      Properties.Alignment.Horz = taRightJustify
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsUnderline]
      Style.HotTrack = False
      TabOrder = 13
      OnClick = lblPresetClick
      OnMouseEnter = cxLabelMouseEnterWhite
      OnMouseLeave = cxLabelMouseLeaveWhite
    end
    object lblClose: TcxLabel
      Left = 175
      Top = 205
      Width = 30
      Height = 17
      Cursor = crHandPoint
      Caption = 'Close'
      ParentColor = False
      ParentFont = False
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsUnderline]
      Style.HotTrack = False
      TabOrder = 14
      OnClick = lblCloseClick
      OnMouseEnter = cxLabelMouseEnterWhite
      OnMouseLeave = cxLabelMouseLeaveWhite
    end
    object trackEQ01: TcxTrackBar
      Tag = 1
      Left = 30
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 1
    end
    object trackEQ02: TcxTrackBar
      Tag = 2
      Left = 58
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 2
    end
    object trackEQ03: TcxTrackBar
      Tag = 3
      Left = 87
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 3
    end
    object trackEQ04: TcxTrackBar
      Tag = 4
      Left = 116
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 4
    end
    object trackEQ05: TcxTrackBar
      Tag = 5
      Left = 145
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 5
    end
    object trackEQ06: TcxTrackBar
      Tag = 6
      Left = 173
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 6
    end
    object trackEQ07: TcxTrackBar
      Tag = 7
      Left = 201
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 7
    end
    object trackEQ08: TcxTrackBar
      Tag = 8
      Left = 229
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 8
    end
    object trackEQ09: TcxTrackBar
      Tag = 9
      Left = 258
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 9
    end
    object trackEQ10: TcxTrackBar
      Tag = 10
      Left = 287
      Top = 73
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 5
      Properties.Max = 30
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEQPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 10
    end
    object chkUseEQ: TcxCheckBox
      Left = 220
      Top = 36
      Width = 30
      Height = 21
      ParentColor = False
      ParentFont = False
      Properties.Alignment = taCenter
      Properties.DisplayUnchecked = 'False'
      Properties.ImmediatePost = True
      Properties.Caption = ''
      Style.BorderColor = 10526880
      Style.BorderStyle = ebsSingle
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      TabOrder = 0
      OnClick = chkUseEQClick
    end
    object dxLayoutGroup17: TdxLayoutGroup
      ShowCaption = False
      Hidden = True
      ShowBorder = False
      object dxLayoutGroup18: TdxLayoutGroup
        AutoAligns = []
        AlignHorz = ahClient
        AlignVert = avClient
        Caption = 'Sign In'
        CaptionOptions.AlignHorz = taCenter
        LookAndFeel = datMain.layoutLookFeelMain_WebAlt5
        ShowCaption = False
        object dxLayoutItem19: TdxLayoutItem
          ShowCaption = False
          Control = Panel37
          ControlOptions.ShowBorder = False
        end
        object layoutEqualizerItem2: TdxLayoutItem
          AutoAligns = [aaVertical]
          AlignHorz = ahCenter
          Caption = 'Use Graphic Equalizer:'
          CaptionOptions.AlignHorz = taCenter
          Offsets.Top = 10
          Control = chkUseEQ
          ControlOptions.AutoColor = True
          ControlOptions.ShowBorder = False
        end
        object layoutEqualizerGroup1: TdxLayoutGroup
          AutoAligns = []
          AlignHorz = ahCenter
          AlignVert = avClient
          Caption = 'New Group'
          Offsets.Top = 10
          ShowCaption = False
          Hidden = True
          LayoutDirection = ldHorizontal
          ShowBorder = False
          object layoutEqualizerItem3: TdxLayoutItem
            AutoAligns = [aaVertical]
            Caption = '80'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Control = trackEQ01
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem7: TdxLayoutItem
            Caption = '170'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ02
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem8: TdxLayoutItem
            Caption = '310'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ03
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem9: TdxLayoutItem
            Caption = '600'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ04
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem10: TdxLayoutItem
            Caption = '1K'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ05
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem11: TdxLayoutItem
            Caption = '3K'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ06
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem12: TdxLayoutItem
            Caption = '6K'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ07
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem13: TdxLayoutItem
            Caption = '10K'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ08
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem14: TdxLayoutItem
            Caption = '12K'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ09
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem15: TdxLayoutItem
            Caption = '14K'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clBottom
            Offsets.Left = 1
            Control = trackEQ10
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
        end
        object layoutEqualizerGroup3: TdxLayoutGroup
          AutoAligns = []
          AlignHorz = ahCenter
          AlignVert = avBottom
          Caption = 'New Group'
          ShowCaption = False
          LayoutDirection = ldHorizontal
          ShowBorder = False
          object layoutEqualizerItem4: TdxLayoutItem
            AutoAligns = [aaVertical]
            ShowCaption = False
            Control = lblPreset
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutEqualizerItem1: TdxLayoutItem
            AutoAligns = [aaVertical]
            AlignHorz = ahRight
            Caption = 'cxLabel1'
            ShowCaption = False
            Control = lblClose
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
        end
        object dxLayoutItem21: TdxLayoutItem
          AutoAligns = [aaHorizontal]
          AlignVert = avBottom
          ShowCaption = False
          Control = Panel38
          ControlOptions.ShowBorder = False
        end
      end
    end
  end
  object titleMain: TFlatTitlebar
    Left = 0
    Top = 0
    Width = 340
    Height = 18
    ActiveTextColor = clWhite
    InactiveTextColor = clSilver
    TitlebarColor = clGray
    Align = alTop
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    Caption = 'Equalizer'
  end
  object barEQ: TdxBarManager
    AllowReset = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    Bars = <>
    CanCustomize = False
    Categories.Strings = (
      'Default')
    Categories.ItemsVisibles = (
      2)
    Categories.Visibles = (
      True)
    ImageListBkColor = clBlack
    LargeImages = datMain.imglstMain_24
    MenusShowRecentItemsFirst = False
    PopupMenuLinks = <>
    Style = bmsFlat
    UseSystemFont = False
    Left = 24
    Top = 45
    DockControlHeights = (
      0
      0
      0
      0)
    object mnuReset: TdxBarButton
      Caption = 'Reset'
      Category = 0
      Hint = 'Reset'
      Visible = ivAlways
      OnClick = mnuResetClick
    end
  end
  object popmnuPreset: TdxBarPopupMenu
    BarManager = barEQ
    ItemLinks = <
      item
        Item = mnuReset
        Visible = True
      end>
    UseOwnFont = False
    Left = 260
    Top = 47
  end
end
