object frmSoundEffectsDLG: TfrmSoundEffectsDLG
  Left = 704
  Top = 251
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'Sound Effects'
  ClientHeight = 266
  ClientWidth = 340
  Color = 15790320
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object layoutSoundEffects: TdxLayoutControl
    Left = 0
    Top = 18
    Width = 340
    Height = 248
    Align = alClient
    ParentBackground = True
    TabOrder = 0
    AutoContentSizes = [acsWidth, acsHeight]
    LookAndFeel = datMain.layoutLookFeelMain_Web
    object Panel37: TPanel
      Left = 4
      Top = 7
      Width = 150
      Height = 13
      BevelOuter = bvNone
      Color = 10526880
      TabOrder = 5
    end
    object Panel38: TPanel
      Left = 4
      Top = 228
      Width = 150
      Height = 13
      BevelOuter = bvNone
      Color = 10526880
      TabOrder = 6
    end
    object lblReset: TcxLabel
      Left = 136
      Top = 205
      Width = 32
      Height = 17
      Cursor = crHandPoint
      Caption = 'Reset'
      ParentColor = False
      ParentFont = False
      Properties.Alignment.Horz = taRightJustify
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsUnderline]
      Style.HotTrack = False
      TabOrder = 7
      OnClick = lblResetClick
      OnMouseEnter = cxLabelMouseEnterWhite
      OnMouseLeave = cxLabelMouseLeaveWhite
    end
    object lblClose: TcxLabel
      Left = 174
      Top = 205
      Width = 30
      Height = 17
      Cursor = crHandPoint
      Caption = 'Close'
      ParentColor = False
      ParentFont = False
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = [fsUnderline]
      Style.HotTrack = False
      TabOrder = 8
      OnClick = lblCloseClick
      OnMouseEnter = cxLabelMouseEnterWhite
      OnMouseLeave = cxLabelMouseLeaveWhite
    end
    object trackEcho: TcxTrackBar
      Left = 96
      Top = 36
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 8
      Properties.Max = 32
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackEchoPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 0
    end
    object trackReverb: TcxTrackBar
      Tag = 2
      Left = 179
      Top = 36
      Width = 21
      Height = 100
      Cursor = crHandPoint
      ParentColor = False
      ParentFont = False
      Properties.AutoSize = False
      Properties.Frequency = 8
      Properties.Max = 32
      Properties.Orientation = tboVertical
      Properties.TextOrientation = tbtoVertical
      Properties.SelectionColor = clWhite
      Properties.TickColor = clWhite
      Properties.TickMarks = cxtmBoth
      Properties.TickSize = 1
      Properties.TrackColor = clWhite
      Properties.ThumbHeight = 10
      Properties.ThumbWidth = 10
      Properties.ThumbColor = clWhite
      Properties.ThumbHighlightColor = clWhite
      Properties.ThumbStep = cxtsJump
      Properties.OnChange = trackReverbPropertiesChange
      Style.BorderColor = clWhite
      Style.BorderStyle = ebsNone
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      Style.Shadow = False
      Style.TransparentBorder = True
      TabOrder = 2
    end
    object chkEcho: TcxCheckBox
      Left = 55
      Top = 142
      Width = 30
      Height = 21
      ParentColor = False
      ParentFont = False
      Properties.Alignment = taCenter
      Properties.DisplayUnchecked = 'False'
      Properties.ImmediatePost = True
      Properties.Caption = ''
      Style.BorderColor = 10526880
      Style.BorderStyle = ebsSingle
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      TabOrder = 1
      OnClick = chkEchoClick
    end
    object chkReverb: TcxCheckBox
      Left = 123
      Top = 142
      Width = 30
      Height = 21
      ParentColor = False
      ParentFont = False
      Properties.Alignment = taCenter
      Properties.DisplayUnchecked = 'False'
      Properties.ImmediatePost = True
      Properties.Caption = ''
      Style.BorderColor = 10526880
      Style.BorderStyle = ebsSingle
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      TabOrder = 3
      OnClick = chkReverbClick
    end
    object chkFlanger: TcxCheckBox
      Left = 206
      Top = 142
      Width = 30
      Height = 21
      ParentColor = False
      ParentFont = False
      Properties.Alignment = taCenter
      Properties.DisplayUnchecked = 'False'
      Properties.ImmediatePost = True
      Properties.Caption = ''
      Style.BorderColor = 10526880
      Style.BorderStyle = ebsSingle
      Style.Color = 5987163
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWhite
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.HotTrack = False
      TabOrder = 4
      OnClick = chkFlangerClick
    end
    object dxLayoutGroup17: TdxLayoutGroup
      ShowCaption = False
      Hidden = True
      ShowBorder = False
      object dxLayoutGroup18: TdxLayoutGroup
        AutoAligns = []
        AlignHorz = ahClient
        AlignVert = avClient
        Caption = 'Sign In'
        CaptionOptions.AlignHorz = taCenter
        LookAndFeel = datMain.layoutLookFeelMain_WebAlt5
        ShowCaption = False
        object dxLayoutItem19: TdxLayoutItem
          ShowCaption = False
          Control = Panel37
          ControlOptions.ShowBorder = False
        end
        object layoutSoundEffectsGroup1: TdxLayoutGroup
          AutoAligns = []
          AlignHorz = ahCenter
          AlignVert = avClient
          Caption = 'New Group'
          Offsets.Top = 10
          ShowCaption = False
          Hidden = True
          LayoutDirection = ldHorizontal
          ShowBorder = False
          object layoutSoundEffectsGroup2: TdxLayoutGroup
            ShowCaption = False
            Hidden = True
            ShowBorder = False
            object layoutSoundEffectsItem3: TdxLayoutItem
              AutoAligns = [aaVertical]
              AlignHorz = ahRight
              CaptionOptions.AlignHorz = taCenter
              CaptionOptions.Layout = clBottom
              Control = trackEcho
              ControlOptions.AutoColor = True
              ControlOptions.ShowBorder = False
            end
            object layoutSoundEffectsItem2: TdxLayoutItem
              AutoAligns = [aaVertical]
              Caption = 'Echo'
              CaptionOptions.AlignHorz = taCenter
              CaptionOptions.Layout = clRight
              Control = chkEcho
              ControlOptions.AutoColor = True
              ControlOptions.ShowBorder = False
            end
          end
          object layoutSoundEffectsGroup4: TdxLayoutGroup
            ShowCaption = False
            Hidden = True
            ShowBorder = False
            object layoutSoundEffectsItem7: TdxLayoutItem
              AutoAligns = [aaVertical]
              AlignHorz = ahRight
              CaptionOptions.AlignHorz = taCenter
              CaptionOptions.Layout = clBottom
              Offsets.Left = 1
              Control = trackReverb
              ControlOptions.AutoColor = True
              ControlOptions.ShowBorder = False
            end
            object layoutSoundEffectsItem5: TdxLayoutItem
              AlignmentConstraint = layoutSoundEffectsAlignmentConstraint1
              Caption = 'Reverb'
              CaptionOptions.AlignHorz = taCenter
              CaptionOptions.Layout = clRight
              Control = chkReverb
              ControlOptions.AutoColor = True
              ControlOptions.ShowBorder = False
            end
          end
          object layoutSoundEffectsItem6: TdxLayoutItem
            AlignmentConstraint = layoutSoundEffectsAlignmentConstraint1
            Caption = 'Flanger'
            CaptionOptions.AlignHorz = taCenter
            CaptionOptions.Layout = clRight
            Control = chkFlanger
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
        end
        object layoutSoundEffectsGroup3: TdxLayoutGroup
          AutoAligns = []
          AlignHorz = ahCenter
          AlignVert = avBottom
          Caption = 'New Group'
          ShowCaption = False
          LayoutDirection = ldHorizontal
          ShowBorder = False
          object layoutSoundEffectsItem4: TdxLayoutItem
            AutoAligns = [aaVertical]
            ShowCaption = False
            Control = lblReset
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
          object layoutSoundEffectsItem1: TdxLayoutItem
            AutoAligns = [aaVertical]
            AlignHorz = ahRight
            Caption = 'cxLabel1'
            ShowCaption = False
            Control = lblClose
            ControlOptions.AutoColor = True
            ControlOptions.ShowBorder = False
          end
        end
        object dxLayoutItem21: TdxLayoutItem
          AutoAligns = [aaHorizontal]
          AlignVert = avBottom
          ShowCaption = False
          Control = Panel38
          ControlOptions.ShowBorder = False
        end
      end
    end
    object layoutSoundEffectsAlignmentConstraint1: TdxLayoutAlignmentConstraint
      Kind = ackTop
    end
  end
  object titleMain: TFlatTitlebar
    Left = 0
    Top = 0
    Width = 340
    Height = 18
    ActiveTextColor = clWhite
    InactiveTextColor = clSilver
    TitlebarColor = clGray
    Align = alTop
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    Caption = 'Sound Effects'
  end
end
