CREATE TABLE `tblArtists` (
  `ID` int(11) NOT NULL auto_increment,
  `Name` varchar(100) NOT NULL default '',
  `Genre_ID` int(11) default NULL,
  `SubGenre_ID` int(11) default NULL,
  `DateCreated` date NOT NULL default '0000-00-00',
  `WebsiteURL` varchar(255) default NULL,
  `RecLabel_ID` int(11) default NULL,
  `Location_ID` int(11) default NULL,
  `IMGPath` varchar(255) default NULL,
  `ProfilePic` varchar(255) default NULL,
  `City` varchar(100) default NULL,
  `State` char(2) default NULL,
  `Country` varchar(100) default NULL,
  `Active` tinyint(4) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `ID` (`ID`),
  KEY `Name` (`Name`),
  KEY `Genre_ID` (`Genre_ID`),
  KEY `SubGenre_ID` (`SubGenre_ID`),
  KEY `DateCreated` (`DateCreated`),
  KEY `Location_ID` (`Location_ID`),
  KEY `Active` (`Active`),
) TYPE=MyISAM; 


CREATE TABLE `tblAlbums` (
  `ID` int(11) NOT NULL auto_increment,
  `Title` varchar(100) NOT NULL default '',
  `Artist_ID` int(11) default NULL,
  `Genre_ID` int(11) default NULL,
  `SubGenre_ID` int(11) default NULL,
  `RecLabel_ID` int(11) default NULL,
  `TotalLength` varchar(10) NOT NULL default '',
  `TotalTracks` int(11) default NULL,
  `DateCreated` date NOT NULL default '0000-00-00',
  `DateReleased` date NOT NULL default '0000-00-00',
  `Price_ID` int(11) default NULL,
  `IMGPath` varchar(255) default NULL,
  `Active` tinyint(4) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `ID` (`ID`),
  KEY `Title` (`Title`),
  KEY `Artist_ID` (`Artist_ID`),
  KEY `Genre_ID` (`Genre_ID`),
  KEY `SubGenre_ID` (`SubGenre_ID`),
  KEY `DateCreated` (`DateCreated`),
  KEY `DateReleased` (`DateReleased`),
  KEY `Active` (`Active`),
) TYPE=MyISAM; 

CREATE TABLE `tblTracks` (
  `ID` int(11) NOT NULL auto_increment,
  `Artist_ID` int(11) default NULL,
  `Album_ID` int(11) default NULL,
  `Genre_ID` int(11) default NULL,
  `TrackNum` int(11) default NULL,
  `Title` varchar(100) NOT NULL default '',
  `Length` varchar(10) NOT NULL default '',
  `ListenLimit` int(11) default NULL,
  `StreamPath` varchar(255) default NULL,
  `DLPath` varchar(255) default NULL,
  `DateCreated` date NOT NULL default '0000-00-00',
  `Price_ID` int(11) default NULL,
  `Channels` varchar(10) default NULL,
  `SampleRate` varchar(20) default NULL,
  `BitRate` varchar(10) default NULL,
  `Active` tinyint(4) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `ID` (`ID`),
  KEY `Artist_ID` (`Artist_ID`),
  KEY `Album_ID` (`Album_ID`),
  KEY `Genre_ID` (`Genre_ID`),
  KEY `Title` (`Title`),
  KEY `DateCreated` (`DateCreated`),
  KEY `Active` (`Active`),
) TYPE=MyISAM; 
